/**
 * Data Source Configuration
 * This file is auto-generated by GitHub Actions during deployment
 * DO NOT EDIT MANUALLY
 *
 * Data files are served from the same static site deployment.
 */

const DATA_CONFIG = {
    /**
     * GitHub repository owner (username)
     * This will be replaced during GitHub Actions workflow execution
     */
    repoOwner: 'xiaoqixiaowei',

    /**
     * GitHub repository name
     * This will be replaced during GitHub Actions workflow execution
     */
    repoName: 'daily-arxiv-ai',

    /**
     * Data branch name
     * Default: 'data'
     */
    dataBranch: 'data',

    /**
     * Get the base URL for static data files
     * @returns {string} Base URL for static data files
     */
    getDataBaseUrl: function() {
        return '.';
    },

    /**
     * Get the full URL for a data file
     * @param {string} filePath - Relative path to the data file (e.g., 'data/2025-01-01.jsonl')
     * @returns {string} Full URL to the data file
     */
    getDataUrl: function(filePath) {
        return `${this.getDataBaseUrl()}/${filePath}`;
    }
};
